version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  mongodb:
    image: 'mongo:4.4'
    ports:
      - '27018:27017'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - mongodb
